### ISSUE TITLE
Getting this error in my console, any help would be very much apreciated :)

### ISSUE THREAD

**Issue by OEM0VER** [ESX-PUBLIC/esx_jailer#32]
Creating script environments for esx_jail
Error loading script server/main.lua in resource esx_jail: @esx_jail/server/main.lua:38: attempt to call a nil value (field 'RegisterCommand')
stack traceback:
        @esx_jail/server/main.lua:38: in main chunk
Failed to load script server/main.lua.

**Comment by rex2630** [comment]
Update your ESX

**Comment by lashley7** [comment]
What exactly do you mean by "update your ESX"? - I am having exactly the same problem, but I cannot seem to get the script working at all. 

Error I am personally getting - 

Creating script enviroments for esx_jail
Error parsing script @esx_jail/config.lua in resource esx_jail: @esx_jail/config.lua:2: unexpected symbol near '['
failed to load script config.lua.
Error loading script server/main.lua in resource esx_jail:@esx_jail/server/main.lua:38: attempt to call a nil value (field 'RegisterCommand')
@esx_jail/server/main.lua:38: in main chunck
Failed to load script server/main.lua.
Started resource esx_jail

Error 1 - 
So I have checked the config/lua:2 - There is no unexpected symbol there. Nor is there anything in there that shouldn't be.

Error 2 - 
Is what @OEM0VER is experiencing above. Is there anyway we can get an answer to this asap cause there server is literally unplayable without a jail in the current state.

@rex2630 - could you please help us out?

**Comment by lashley7** [comment]
Checked over the script, there was a unexpected symbol there. ['en'] - error 1 is fixed.

**Comment by lashley7** [comment]
Checked over the script, there was a unexpected symbol there. ['en'] - error 1 is fixed.

**Comment by rex2630** [comment]
What? Where is the error in translation? Did u fixed it? And if not do u have latest es_extended?

**Comment by OEM0VER** [comment]
Sorry people for the lack of interest, I gave up on trying to make this script work and ended up going with a more noob friendly script called "jailer 1.1.0.0". Hope this helps if you cannot get it working at all.

**Comment by lashley7** [comment]
@rex2630 I can confirm I am running es_extended. @OEM0VER no worries, could we keep this thread open?

**Comment by rex2630** [comment]
What? Im asking if u are running latest version! Oh, gosh

**Comment by OEM0VER** [comment]
I believe my esx version is 6.2.2

**Comment by lashley7** [comment]
@rex2630 1.1 is the "es_extended" version I'm running

**Comment by rex2630** [comment]
This script works only for ESX v1.2+
